//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciKayit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Dersler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dersler()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
    
        public int DersID { get; set; }
        public string Ad { get; set; }
        public string Kodu { get; set; }
        public bool Aktif { get; set; }
        public int Uygulama { get; set; }
        public int Teorik { get; set; }
        public int Laboratuvar { get; set; }
        public double Kredi { get; set; }
        public double EctsKredi { get; set; }
        public int ZorunluSecmeli { get; set; }
        public int YıllıkDonemlik { get; set; }
        public Nullable<int> Donemi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
    public enum ZorunluSecmeli
    {
        [Display(Name = "Zorunlu")]
        Zorunlu = 0,
        [Display(Name = "Seçmeli")]
        Secmeli = 1

    }
    public enum YillikDonemlik
    {
        [Display(Name = "Yıllık")]
        Yillik = 0,
        [Display(Name = "Dönemlik")]
        Donemlik = 1

    }
}
