//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciKayit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Ogrenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogrenci()
        {
            this.OgrenciDers = new HashSet<OgrenciDers>();
        }
        
        public int OgrenciID { get; set; }
        public string OgrenciNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string TcKimlikNo { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string Uyrugu { get; set; }
        public string Fakulte { get; set; }
        public string Bolum { get; set; }
        public int Sinif { get; set; }
        public string Mufredat { get; set; }
        public Nullable<System.DateTime> MezuniyetTarihi { get; set; }
        public string BitirdigiUniversite { get; set; }
        public string Yariyili { get; set; }
        public string EgitimTuru { get; set; }
        public string BorclulukDurumu { get; set; }
        public string KulupUyeligi { get; set; }
        public string KayitlanmaSekli { get; set; }
        public string KayitlanmaPuani { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> KayitlanmaYili { get; set; }
        public Nullable<int> KayitDonemi { get; set; }
        public string LiseMezuniyeti { get; set; }
        public string LiseMezuniyetiPuani { get; set; }
        public string Cinsiyet { get; set; }
        public string AskerlikDurumu { get; set; }
        public string EngellilikDurumu { get; set; }
        public Nullable<int> OrganizasyonID { get; set; }
        public string Fotograf { get; set; }
        public Nullable<bool> OgrHak { get; set; }
        public string AnneAd { get; set; }
        public string BabaAd { get; set; }
        public Nullable<int> OgrSure { get; set; }
    
        public virtual Organizasyon Organizasyon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciDers> OgrenciDers { get; set; }
    }
    public enum Yariyil
    {
        [Display(Name = "1")]
        birinci = 1,
        [Display(Name = "2")]
        ikinci = 2

    }
    public enum Cinsiyet
    {
        [Display(Name = "Erkek")]
        Erkek = 0,
        [Display(Name = "Kadýn")]
        Kadýn = 1

    }
    public enum EgitimTuru
    {
        [Display(Name = "Örgün")]
        orgun = 0,
        [Display(Name = "Ýkinci")]
        ikinci = 1,
        [Display(Name = "Uzaktan")]
        Uzaktan = 2

    }
    public enum EvetHayir
    {
        [Display(Name = "Evet")]
        evet = 1,
        [Display(Name = "Hayir")]
        hayir = 0,

    }

}
