//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OgrenciKayit.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class OgrenciDers
    {
        public int ID { get; set; }
        
        public int OgrenciID { get; set; }
        public int DersID { get; set; }
        public string Yil { get; set; }
        public string Donem { get; set; }
        public Nullable<int> Vize { get; set; }
        public Nullable<int> MazeretVize { get; set; }
        public Nullable<int> Final { get; set; }
        public Nullable<int> Butunleme { get; set; }
        public Nullable<int> TekDers { get; set; }
        public Nullable<int> BasariNotu { get; set; }
        public string HarfNotu { get; set; }
    
        public virtual Dersler Dersler { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
    public enum Donem
    {
        [Display(Name = "Güz")]
        Guz = 0,
        [Display(Name = "Bahar")]
        Bahar = 1,
        [Display(Name = "Yaz")]
        Yaz = 2
    }
}
